[package]
name = "runst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freedesktop_entry_parser = "1.3.0"
gdk = "0.18.0"
gtk = { version = "0.7.2", package = "gtk4", features = ["v4_12"] }
